version: '3.11'

services:
  smoke:
    image: python:3.11-alpine
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
    command: /bin/sh -c "ls -la && pytest -sv -m smoke --alluredir=allure-results"
    working_dir: /usr/workspace
    environment:
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}

  regression:
    image: python:3.11-alpine
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
    command: /bin/sh -c "ls -la && pytest -sv --alluredir=allure-results"
    working_dir: /usr/workspace
    environment:
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}



